In [8]:
import pandas as pd

In [12]:
df= pd.read_csv('police.csv')

In [11]:
df

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   county_name         0 non-null      float64
 3   driver_gender       86406 non-null  object
 4   driver_age_raw      86414 non-null  float64
 5   driver_age          86120 non-null  float64
 6   driver_race         86408 non-null  object
 7   violation_raw       86408 non-null  object
 8   violation           86408 non-null  object
 9   search_conducted    91741 non-null  bool
 10  search_type         3196 non-null   object
 11  stop_outcome        86408 non-null  object
 12  is_arrested         86408 non-null  object
 13  stop_duration       86408 non-null  object
 14  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(3), object(10)
memory usage: 9.3+ MB

In [13]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
91736    False
91737    False
91738    False
91739    False
91740    False
Length: 91741, dtype: bool

In [18]:
df.drop_duplicates(inplace = True)

In [20]:
del df['county_name']

In [22]:
del df['stop_time']

In [24]:
df['stop_date']=pd.to_datetime(df['stop_date'])

In [26]:
df.fillna({'search_type': 'Not specified'}, inplace=True)

In [28]:
df.dropna(inplace = True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 85845 entries, 0 to 91740
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           85845 non-null  datetime64[ns]
 1   driver_gender       85845 non-null  object
 2   driver_age_raw      85845 non-null  float64
 3   driver_age          85845 non-null  float64
 4   driver_race         85845 non-null  object
 5   violation_raw       85845 non-null  object
 6   violation           85845 non-null  object
 7   search_conducted    85845 non-null  bool
 8   search_type         85845 non-null  object
 9   stop_outcome        85845 non-null  object
 10  is_arrested         85845 non-null  object
 11  stop_duration       85845 non-null  object
 12  drugs_related_stop  85845 non-null  bool
dtypes: bool(2), datetime64[ns](1), float64(2), object(8)
memory usage: 8.0+ MB

In [65]:
df.to_csv('Cleaned_police.csv',index=False)